In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5])
print(np1.shape)

(5,)


In [3]:
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np3 = np.arange(2,10)
print(np3)

[2 3 4 5 6 7 8 9]


In [5]:
np4 = np.arange(2,10, 3)
print(np4)

[2 5 8]


In [6]:
np5 = np.zeros(10)
print(np5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
np6 = np.zeros((3,8))
print(np6)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
np7 = np.full(7,2)
print(np7)

[2 2 2 2 2 2 2]


In [9]:
np8 = np.full((2,7),2)
print(np8)

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


In [11]:
myList = [1,2,3,4,5]
np9 = np.array(myList)
print(np9)

[1 2 3 4 5]


In [12]:
np9[0]

1