In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1)

[1 2 3 4 5 6 7 8 9]


In [3]:
print(np1[1:4])

[2 3 4]


In [4]:
print(np1[4:])

[5 6 7 8 9]


In [5]:
print(np1[-4:])

[6 7 8 9]


In [6]:
print(np1[-4:-2])

[6 7]


In [7]:
print(np1[1:5:2])

[2 4]


In [8]:
print(np1[::2])

[1 3 5 7 9]


In [10]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)
print(np2[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [11]:
print(np2[0:1, 1:3])

[[2 3]]


In [12]:
print(np2[0:2, 1:3])

[[2 3]
 [7 8]]
