In [1]:
import numpy as np
np1 = np.array([0,1,2,3,4,5,6,7])
print(np1, np1.shape)

[0 1 2 3 4 5 6 7] (8,)


In [2]:
np2 = np.array([[1,2,3,4],[5,6,7,8]])
print(np2, np2.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [3]:
# reshape() takes 3 arguments (x,y,z) --> shape(x,y) and order(z)
# shape --> (row, col), order --> (no of z-axis elements)

In [4]:
# reshape to 2-D
np3 = np1.reshape((2,4))
print(np3, np3.shape)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)


In [5]:
# reshape to 3-D
np4 = np1.reshape(2,2,2)
print(np4, np4.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)


In [7]:
# flatten to 1-D
np5 = np4.reshape(-1)
print(np5, np5.shape)

[0 1 2 3 4 5 6 7] (8,)
