In [1]:
import numpy as np
np1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [11]:
x = np.where(np1&1) # odd items
print(x)
print(x[0])

(array([1, 3, 5, 7, 9], dtype=int64),)
[1 3 5 7 9]


In [15]:
x = np.where(np1&1 == 0) # even items
print(x[0])

[0 2 4 6 8]
