In [1]:
import numpy as np

# np.sort()  Numerical
np1 = np.array([6,7,4,9,0,2,1])

In [2]:
print(np1)
print(np.sort(np1))
print(np1)

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1]


In [3]:
# 2-d
np2 = np.array([[6,7,1,9],[8,3,5,0]])
print(np2)
print(np.sort(np2))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]
