In [1]:
import numpy as np

# Filtering Numpy Arrays With Boolean Index Lists
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [2]:
x = [True, False, True, True, False, False, False, False, False, False]
print(np1[x])

[1 3 4]


In [3]:
filtered = []
for it in np1:
    if(it&1 == 0):
        filtered.append(True)
    else:
        filtered.append(False)
print(filtered)

[False, True, False, True, False, True, False, True, False, True]


In [4]:
print(np1[filtered])

[ 2  4  6  8 10]


In [6]:
filtered2 = np1&1 == 0
print(np1)
print(filtered2)
print(np1[filtered2])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
